myNextApplication:
  component: serverless-next.js@1.10.0
  inputs:
    memory: 1024
    # domain: "stanforddaily.com" # sub-domain defaults to www
    build:
      cmd: expo build-web
      enabled: false
    cloudfront:
      comment: "Stanford Daily website"
      defaults:
        ttl: 60
        compress: true
